"""history add name&type

Revision ID: 38416ff576ce
Revises: 3075126952bc
Create Date: 2025-03-17 08:54:23.906985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38416ff576ce'
down_revision = '3075126952bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('history', sa.Column('type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'type')
    op.drop_column('history', 'name')
    # ### end Alembic commands ###
